// angular/tic-tac-toe/src/app/tic-tac-toe/tic-tac-toe.component.ts
import { Component, OnInit } from '@angular/core';

const players = ['X', 'O']

function getStatus(move, winner, draw) {
  return winner ? `${winner} won` : (draw ? 'Draw' : `${players[(move || 0) % 2]} plays`)
}

function getPosition(square) {
  const row = square.closest('.row')
  const board = row.closest('.board')
  return {
    row: Array.prototype.indexOf.call(board.querySelectorAll('.row'), row),
    column: Array.prototype.indexOf.call(row.querySelectorAll('.square'), square)
  }
}

function getWinner(board, row, column) {
  const horizontal = Array.from(Array(3), (value, index) => ({row: row, column: index}))
  const vertical = Array.from(Array(3), (value, index) => ({row: index, column: column}))
  const diagonal1 = (row === column) && Array.from(Array(3), (value, index) => ({row: index, column: index}))
  const diagonal2 = (row === (2 - column)) && Array.from(Array(3), (value, index) => ({row: index, column: 2 - index}))
  const checks = [horizontal, vertical, diagonal1, diagonal2].filter(item => item)
  const player = board[row][column]
  return checks.some(array => array.every(item => board[item.row][item.column] === player)) ? player : null
}

@Component({
  selector: 'app-tic-tac-toe',
  templateUrl: './tic-tac-toe.component.html',
  styleUrls: [ './tic-tac-toe.component.css' ]
})
export class TicTacToeComponent implements OnInit {
  status = getStatus(0, null, false);
  board = Array.from(Array(3), () => Array(3).fill(''));
  move = 0;
  winner = null;
  draw = false;

  constructor() {
  }

  ngOnInit() {
  }

  mark(event) {
    if (this.winner || this.draw) {
      return
    }
    const { row, column } = getPosition(event.target)
    if (this.board[row][column]) {
      return
    }
    const board = this.board.map(array => array.map(item => item))
    const player = players[this.move % 2]
    board[row][column] = player
    const winner = getWinner(board, row, column)
    const draw = !winner && this.move === 8
    const move = this.move + ((!winner && !draw) ? 1 : 0)
	
    this.status = getStatus(move, winner, draw)
    this.board = board
    this.move = move
    this.winner = winner
    this.draw = draw
  }
}
<div class="tic-tac-toe">
  <p class="status">{{status}}</p>
  <div class="board" (click)="mark($event)">
    <div class="row">
      <button class="square">{{board[0][0]}}</button>
      <button class="square">{{board[0][1]}}</button>
      <button class="square">{{board[0][2]}}</button>
    </div>
    <div class="row">
      <button class="square">{{board[1][0]}}</button>
      <button class="square">{{board[1][1]}}</button>
      <button class="square">{{board[1][2]}}</button>
    </div>
    <div class="row">
      <button class="square">{{board[2][0]}}</button>
      <button class="square">{{board[2][1]}}</button>
      <button class="square">{{board[2][2]}}</button>
    </div>
  </div>
</div>

// react/tic-tac-toe/src/tic-tac-toe.js
import React from 'react'
import './tic-tac-toe.css'

export default class TicTacToe extends React.Component {

  constructor(props) {
    super(props)
    this.players = ['X', 'O']
    this.state = {
      status: this.getStatus(),
      board: Array.from(Array(3), () => Array(3).fill('')),
      move: 0,
      winner: null,
      draw: false
    }
  }

  render() {
    return (
      <div className="tic-tac-toe">
        <p className="status">{this.state.status}</p>
        <div className="board" onClick={this.handleClick}>
          <div className="row">
            <button className="square">{this.state.board[0][0]}</button>
            <button className="square">{this.state.board[0][1]}</button>
            <button className="square">{this.state.board[0][2]}</button>
          </div>
          <div className="row">
            <button className="square">{this.state.board[1][0]}</button>
            <button className="square">{this.state.board[1][1]}</button>
            <button className="square">{this.state.board[1][2]}</button>
          </div>
          <div className="row">
            <button className="square">{this.state.board[2][0]}</button>
            <button className="square">{this.state.board[2][1]}</button>
            <button className="square">{this.state.board[2][2]}</button>
          </div>
        </div>
      </div>
    )
  }

  handleClick = event => {
    if (this.state.winner || this.state.draw) {
      return
    }
    const { row, column } = this.getPosition(event.target)
    if (this.state.board[row][column]) {
      return
    }
    this.setState(prevState => {
      const board = prevState.board.map(array => array.map(item => item))
      const player = this.players[prevState.move % 2]
      board[row][column] = player
      const winner = this.getWinner(board, row, column)
      const draw = !winner && prevState.move === 8
      const move = prevState.move + ((!winner && !draw) ? 1 : 0)
      const status = this.getStatus(move, winner, draw)

      return {
        status: status,
        board: board,
        move: move,
        winner: winner,
        draw: draw
      }
    })
  }

  getStatus(move, winner, draw) {
    return winner ? `${winner} won` : (draw ? 'Draw' : `${this.players[(move || 0) % 2]} plays`)
  }

  getPosition(square) {
    const row = square.closest('.row')
    const board = row.closest('.board')
    return {
      row: Array.prototype.indexOf.call(board.querySelectorAll('.row'), row),
      column: Array.prototype.indexOf.call(row.querySelectorAll('.square'), square)
    }
  }

  getWinner(board, row, column) {
    const horizontal = Array.from(Array(3), (value, index) => ({row: row, column: index}))
    const vertical = Array.from(Array(3), (value, index) => ({row: index, column: column}))
    const diagonal1 = (row === column) && Array.from(Array(3), (value, index) => ({row: index, column: index}))
    const diagonal2 = (row === (2 - column)) && Array.from(Array(3), (value, index) => ({row: index, column: 2 - index}))
    const checks = [horizontal, vertical, diagonal1, diagonal2].filter(item => item)
    const player = board[row][column]
    return checks.some(array => array.every(item => board[item.row][item.column] === player)) ? player : null
  }
}
